### PR TITLE
Bannerlord 1.1.2 compatibility

### PR DESCRIPTION
**Pull request by enisn**
I've just adapted the project to Bannerlord v1.1.2

I hope you'll accept the PR and publish a new version of this mod. Otherwise, I'll go with my own fork if there is no problem on your side👍

### CODE REVIEW

**Comment by curiousdorge** [comment]
How do I download this please? Waiting with bated breath for your response.

**Comment by enisn** [comment]
I just published the binaries for you: https://github.com/enisn/RecruitEveryone/releases/tag/v1.4.0

Download the zip file and extract it into your game's **Modules** folder

**Comment by grosniko** [comment]
Doesn't work for me for some reason, just says "cannot load ...RecruitEveryone.dll" anybody else?

**Comment by Outlaw055** [comment]
> Doesn't work for me for some reason, just says "cannot load ...RecruitEveryone.dll" anybody else?

(SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\Modules\RecruitEveryone\bin\Win64_Shipping_Client) right click Recruiteveryone.dll then go properties tick unblock then apply many mods will require you to do this

**Comment by grosniko** [comment]
YESSSSSSS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by grosniko** [comment]
@enisn could you make this mod work with the charm or leadership skill? like higher xp recruits should be convinced to join with some dialogue. also, would be cool to have the ability to turn off normal troop recruiting and only recruit this way (except maybe fief militia), that would make bannerlord super realistic and really hard. makes it worth it to go into taverns and walk around cities recruiting

**Comment by grosniko** [comment]
i could write the dialogue

**Comment by grosniko** [comment]
image

so i downloaded the code and want to compile, but i get all these erros and warnings. am i missing some package or something?

**Pull request closed without merging**
